[package]
name = "mpl-core-program"
version = "0.1.0"
edition = "2021"
readme = "./README.md"
license-file = "../../LICENSE"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "^0.10"
shank = "0.4.2"
modular-bitfield = "0.11.2"
num-derive = "^0.3"
num-traits = "^0.2"
solana-program = "^1.17"
thiserror = "^1.0"
bytemuck = "1.14.1"
mpl-utils = "0.3.5"
spl-noop = { version = "0.2.0", features = ["cpi"] }
podded = "0.5.1"
strum = { version = "0.26.1", features = ["derive"] }
