/**
 * Shared plumbing for the custom Kinobi renderers in this folder: import
 * accumulation, the autogenerated-file header, and synchronous
 * format-and-write of a render map. Kept in one place so each renderer only
 * contains the logic that is specific to what it renders.
 *
 * Once Kinobi ships `JavaScriptImportMap` and `extraRenderMaps`
 * (metaplex-foundation/kinobi#259) this file can be deleted and both
 * renderers passed straight to `renderJavaScriptVisitor`.
 */
const fs = require("fs");
const path = require("path");
const prettier = require("@prettier/sync");

/** A piece of generated code together with the imports it needs. */
// type Snippet = { code: string; imports?: Array<[module: string, ...names: string[]]> }

function makeImports(order = []) {
    const map = new Map();
    const api = {
        use(from, ...names) {
            if (!map.has(from)) map.set(from, new Set());
            names.forEach((n) => map.get(from).add(n));
            return api;
        },
        /** Register a snippet's imports and return its code. */
        snippet(s) {
            if (!s) return "";
            (s.imports || []).forEach(([from, ...names]) =>
                api.use(from, ...names)
            );
            return s.code;
        },
        render() {
            const seen = [...map.keys()];
            const sorted = [
                ...order.filter((o) => map.has(o)),
                ...seen.filter((s) => !order.includes(s)).sort(),
            ];
            return sorted
                .map((from) => {
                    const names = [...map.get(from)].sort();
                    return `import { ${names.join(", ")} } from '${from}';`;
                })
                .join("\n");
        },
    };
    return api;
}

function header(rendererFile, extra = "") {
    return `/**
 * This code was AUTOGENERATED using a custom Kinobi renderer.
 * Please DO NOT EDIT THIS FILE, instead update the Rust program${extra} or the
 * renderer at \`configs/${rendererFile}\` and rerun kinobi.
 */
`;
}

/** Format every file with prettier and write it under `outDir`. */
function writeRenderMap(files, outDir, prettierConfig) {
    fs.mkdirSync(outDir, { recursive: true });
    Object.entries(files).forEach(([rel, raw]) => {
        const formatted = prettier.format(raw, {
            ...prettierConfig,
            parser: "typescript",
        });
        fs.writeFileSync(path.join(outDir, rel), formatted);
    });
    return Object.keys(files);
}

module.exports = { makeImports, header, writeRenderMap };
